# Generated by Django 5.1.5 on 2026-06-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentePortuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agente portuario',
                'verbose_name_plural': 'Agentes portuarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=15, verbose_name='RUT')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=15, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('tipo', models.CharField(choices=[('20DV', "20' Dry"), ('40DV', "40' Dry"), ('40HC', "40' High Cube"), ('REEF', 'Reefer'), ('OTRO', 'Otro')], default='20DV', max_length=5)),
                ('estado', models.CharField(choices=[('VACIO', 'Vacío'), ('CARGADO', 'Con carga')], default='VACIO', max_length=8)),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ETA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='N° ETA')),
                ('deposito', models.CharField(blank=True, help_text='Ej. Casablanca', max_length=120)),
                ('fecha', models.DateField()),
                ('hora_retiro', models.TimeField(blank=True, null=True)),
                ('tipo_proceso', models.CharField(choices=[('DIRECTO', 'Directo (con almacenaje)'), ('INDIRECTO', 'Indirecto (solo trazabilidad)')], default='DIRECTO', max_length=10)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('ASIGNADO', 'Asignado'), ('EN_PATIO', 'En patio'), ('ALMACENADO', 'Almacenado'), ('DESPACHADO', 'Despachado'), ('CERRADO', 'Cerrado')], default='SOLICITADO', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etas', to='operaciones.agenteportuario')),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etas', to='operaciones.camion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etas', to='operaciones.cliente')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etas', to='operaciones.conductor')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etas', to='operaciones.contenedor')),
            ],
            options={
                'verbose_name': 'ETA',
                'verbose_name_plural': 'ETAs',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('RETIRO', 'Retiro'), ('ALMACENAJE', 'Almacenaje'), ('DESPACHO', 'Despacho'), ('DEVOLUCION', 'Devolución')], max_length=12)),
                ('fecha', models.DateTimeField()),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('eta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='operaciones.eta')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
