# Generated by Django 5.1.5 on 2026-06-12 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('rut', models.CharField(blank=True, max_length=15, verbose_name='RUT')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='responsable',
        ),
        migrations.AddField(
            model_name='eta',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación física en patio (calle/piso/nivel). La registra el jefe de patio cuando el gruero le indica por radio.', max_length=120),
        ),
        migrations.AlterField(
            model_name='eta',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado por cliente'), ('ASIGNADO', 'Asignado'), ('EN_PATIO', 'En patio'), ('ALMACENADO', 'Almacenado'), ('DESPACHADO', 'Despachado'), ('CERRADO', 'Cerrado')], default='SOLICITADO', max_length=12),
        ),
        migrations.AddField(
            model_name='conductor',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa de transporte a la que pertenece el conductor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores', to='operaciones.empresa'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='empresa_responsable',
            field=models.ForeignKey(blank=True, help_text='Empresa responsable del movimiento (lista desplegable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='operaciones.empresa'),
        ),
    ]
