# Generated by Django 5.1.5 on 2026-06-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_estados_cierre_contenedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INOPERATIVO', 'Inoperativo')], default='ACTIVO', help_text='Disponibilidad operativa del conductor (Activo / Inoperativo).', max_length=12),
        ),
        migrations.AddField(
            model_name='eta',
            name='deposito_devolucion',
            field=models.CharField(blank=True, help_text='Depósito donde se devuelve el vacío.', max_length=80),
        ),
        migrations.AddField(
            model_name='eta',
            name='despacho',
            field=models.CharField(blank=True, help_text='N° de despacho del documento operativo.', max_length=30),
        ),
        migrations.AddField(
            model_name='eta',
            name='dimension',
            field=models.CharField(blank=True, help_text="Tipo/dimensión real (ej. '40 HC', '20 DV').", max_length=30),
        ),
        migrations.AddField(
            model_name='eta',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eta',
            name='estado_entrega',
            field=models.CharField(blank=True, choices=[('ENTREGADO', 'Entregado'), ('SIN_LLEGADA', 'Sin llegada'), ('REPROGRAMADO', 'Reprogramado'), ('PENDIENTE', 'Pendiente'), ('NO_ENTREGADO', 'No entregado')], max_length=14),
        ),
        migrations.AddField(
            model_name='eta',
            name='estado_retiro',
            field=models.CharField(blank=True, choices=[('RETIRADO', 'Retirado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado')], max_length=14),
        ),
        migrations.AddField(
            model_name='eta',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eta',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eta',
            name='horario',
            field=models.TimeField(blank=True, help_text='Hora de servicio (retiro/entrega).', null=True),
        ),
        migrations.AddField(
            model_name='eta',
            name='nave',
            field=models.CharField(blank=True, help_text='Motonave (M/N) en que llegó el contenedor.', max_length=80),
        ),
        migrations.AddField(
            model_name='eta',
            name='operacion',
            field=models.CharField(blank=True, choices=[('IMPO', 'Importación'), ('EXPO', 'Exportación')], help_text='IMPO (importación) / EXPO (exportación).', max_length=10),
        ),
        migrations.AddField(
            model_name='eta',
            name='otd',
            field=models.CharField(blank=True, choices=[('ON_TIME', 'On time'), ('OFF_TIME', 'Off time'), ('SIN_LLEGADA', 'Sin llegada')], help_text='Cumplimiento de horario del servicio (On time / Off time).', max_length=12),
        ),
        migrations.AddField(
            model_name='eta',
            name='peso',
            field=models.PositiveIntegerField(blank=True, help_text='Peso en kilogramos.', null=True),
        ),
        migrations.AddField(
            model_name='eta',
            name='puerto',
            field=models.CharField(blank=True, help_text='Puerto/terminal de origen (TPS, STI, DPW...).', max_length=40),
        ),
    ]
